---
# tasks file for sge_master

- name : Create the SGE administrative User
  user:
    name: sgeadmin
    home: /opt/sge
    system: yes

- name: Install SGE Packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ baseurl }}/{{ version }}/gridengine-{{ version }}-{{release}}.el6.x86_64.rpm"
    - "{{ baseurl }}/{{ version }}/gridengine-qmaster-{{ version }}-{{release}}.el6.x86_64.rpm"
    - "{{ baseurl }}/{{ version }}/gridengine-qmon-{{ version }}-{{release}}.el6.x86_64.rpm"
    - "{{ baseurl }}/{{ version }}/gridengine-execd-{{ version }}-{{release}}.el6.x86_64.rpm"

- name: Copy over the configuration template.
  copy:
    src: inst_template.conf
    dest: /tmp/inst_template.conf 

- name: Install master host.
  shell: |
    cd /opt/sge
    ./install_qmaster -auto /tmp/inst_template.conf

- name: Install the root bashrc
  copy:
    src: bashrc
    dest: /root/.bashrc

- name: Add node hostnames to the trusted host list
  shell: |
    . /root/.bashrc
    qconf -ah nodeA
    qconf -ah nodeB

