# SGE Configuration
export SGE_ROOT=/opt/sge
export SGE_CELL=default
if [ -e $SGE_ROOT/$SGE_CELL ]
then
. $SGE_ROOT/$SGE_CELL/common/settings.sh

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi
